import Head from 'next/head'
import { Header } from '../components/Header'

import styles from './home.module.scss';
import ProductsExampler from '../components/Products';
import Footer from '../components/Footer';
import Because from '../components/Because';
import React from 'react';
import HeroBanner from '../components/HeroBanner';

export default function Home() {
  return (
    <>
      <Head>
        <title>Home | PC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <main className={styles.contentContainer}>
        <HeroBanner />
      </main>
      <section className={styles.contentMain}>
        <ProductsExampler />
        <Because />
      </section>
      
      <Footer />
    </>
  )
}
